#!/usr/bin/env python3
"""Regenerate Sources/Swiftcn/Theme/Palette.swift from Tailwind's theme.css.

Usage:
    python3 scripts/generate_palette.py path/to/theme.css

The input is the oklch default palette from the tailwindcss package
(packages/tailwindcss/theme.css), pinned to a release tag, e.g.:
https://raw.githubusercontent.com/tailwindlabs/tailwindcss/v4.1.14/packages/tailwindcss/theme.css

Each oklch value is converted to an 8-bit sRGB hex using the CSS Color 4
gamut-mapping algorithm (OKLCh chroma reduction with clip-within-JND), which
is what browsers and Tailwind's own published sRGB fallbacks use, so the
emitted hexes match Tailwind's documented fallback values byte for byte.
"""

import math
import pathlib
import re
import sys

# The scales swiftcn ships, in Palette.swift order.
SCALES = [
    "slate", "gray", "zinc", "neutral", "stone",
    "red", "orange", "amber", "yellow", "lime",
    "green", "emerald", "teal", "cyan", "sky",
    "blue", "indigo", "violet", "purple", "fuchsia",
    "pink", "rose",
]
STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]

HEADER = """import SwiftUI

// The Tailwind CSS default palette — the shared color vocabulary of every
// swiftcn theme, the same scales shadcn/ui builds its themes from.
// Values are the v4 oklch palette (tailwindcss v4.1.14 theme.css) converted
// to 8-bit sRGB with CSS Color 4 gamut mapping, matching Tailwind's own
// published sRGB fallbacks. Generated by scripts/generate_palette.py;
// do not hand-edit values.
extension Color {
    public init(hex: UInt32) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255
        )
    }
"""


def oklch_to_oklab(light, chroma, hue):
    return (
        light,
        chroma * math.cos(math.radians(hue)),
        chroma * math.sin(math.radians(hue)),
    )


def oklab_to_linear_srgb(light, a, b):
    l_ = light + 0.3963377774 * a + 0.2158037573 * b
    m_ = light - 0.1055613458 * a - 0.0638541728 * b
    s_ = light - 0.0894841775 * a - 1.2914855480 * b
    l, m, s = l_**3, m_**3, s_**3
    return (
        +4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
        -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
        -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s,
    )


def linear_srgb_to_oklab(r, g, b):
    def cbrt(x):
        return x ** (1 / 3) if x >= 0 else -((-x) ** (1 / 3))

    l = cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
    m = cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
    s = cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
    return (
        0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s,
        1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s,
        0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s,
    )


def in_gamut(rgb):
    return all(0 <= c <= 1 for c in rgb)


def clip(rgb):
    return tuple(min(max(c, 0.0), 1.0) for c in rgb)


def css_gamut_map(light, chroma, hue):
    """CSS Color 4 section 13.2: binary search on OKLCh chroma, returning the
    channel-clipped candidate once clipping is imperceptible (deltaEOK < JND)."""
    rgb = oklab_to_linear_srgb(*oklch_to_oklab(light, chroma, hue))
    if in_gamut(rgb):
        return rgb
    if light >= 1:
        return (1.0, 1.0, 1.0)
    if light <= 0:
        return (0.0, 0.0, 0.0)
    jnd, eps = 0.02, 0.0001
    lo, hi = 0.0, chroma
    lo_in_gamut = True
    current = rgb
    while hi - lo > eps:
        mid = (lo + hi) / 2
        current = oklab_to_linear_srgb(*oklch_to_oklab(light, mid, hue))
        if lo_in_gamut and in_gamut(current):
            lo = mid
            continue
        clipped = clip(current)
        delta = math.dist(
            linear_srgb_to_oklab(*clipped), linear_srgb_to_oklab(*current)
        )
        if delta < jnd:
            if jnd - delta < eps:
                return clipped
            lo_in_gamut = False
            lo = mid
        else:
            hi = mid
    return clip(current)


def to_hex(light, chroma, hue):
    def gamma(c):
        return 12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055

    r, g, b = (gamma(c) for c in clip(css_gamut_map(light, chroma, hue)))
    return (round(r * 255) << 16) | (round(g * 255) << 8) | round(b * 255)


def parse_theme(path):
    pattern = re.compile(
        r"--color-([a-z]+)-(\d+):\s*oklch\(([\d.]+)%\s+([\d.]+)\s+([\d.]+)\)"
    )
    colors = {}
    for line in pathlib.Path(path).read_text().splitlines():
        match = pattern.search(line)
        if match:
            name, step, light, chroma, hue = match.groups()
            colors[(name, int(step))] = to_hex(
                float(light) / 100, float(chroma), float(hue)
            )
    return colors


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    colors = parse_theme(sys.argv[1])
    missing = [
        f"{scale}-{step}"
        for scale in SCALES
        for step in STEPS
        if (scale, step) not in colors
    ]
    if missing:
        sys.exit(f"theme.css is missing expected colors: {missing}")

    blocks = []
    for scale in SCALES:
        lines = [
            f"    public static let {scale}{step} = "
            f"Color(hex: 0x{colors[(scale, step)]:06X})"
            for step in STEPS
        ]
        blocks.append("\n".join(lines))

    out = HEADER + "\n" + "\n\n".join(blocks) + "\n}\n"
    target = (
        pathlib.Path(__file__).resolve().parent.parent
        / "Sources/Swiftcn/Theme/Palette.swift"
    )
    target.write_text(out)
    print(f"wrote {target} ({len(SCALES) * len(STEPS)} colors)")


if __name__ == "__main__":
    main()
